name: CI frontend
on:
  push:
    paths:
    - 'workspace/frontend/**'
  pull_request:
    paths:
    - 'workspace/frontend/**'
defaults:
  run:
    working-directory: workspace/frontend
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Run lint command
        run: yarn lint
  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Build Backend
        run: yarn build
        working-directory: workspace/backend
      - name: Run build command
        run: yarn electron:build